Add failing test for named type alias
Currently, Scala doesn't emit named alias types. For WIT functions
that uses type aliases, Scala just dealias types at the boundary.
In the example below, Scala emits `option<u32> -> option<u32>`.

```wit
type option-u32 = option<u32>;
roundtrip-option-u32: func(a: option-u32) -> option-u32;
```

At the canonical ABI, it makes sense, it doesn't care type aliases.
However, at the component instance type checking, type aliases are one
of the `type export` from instance type. We need to export those type
aliases as a named type in order to linking with other components.

It seems `wac plug` just skip plugging if the type didn't match

```bash
wac plug --plug rust-exports/target/wasm32-wasip1/release/rust_exports.wasm .2.13/target/scala-2.13/testing-module-for-component-model-fastopt/main.wasm -o scala.wasm
wac plug --plug scala.wasm rust-run/target/wasm32-wasip1/release/rust_run.wasm -o out.wasm
wasmtime -W function-references,gc,exceptions out.wasm
Error: failed to run main module `out.wasm`

Caused by:
    0: component imports instance `component:testing/tests`, but a matching implementation was not found in the linker
    1: instance export `roundtrip-basics1` has the wrong type
    2: function implementation is missing

make: *** [run] Error 1
```